(() => {
  'use strict';

  const ACTIVE_STATUSES=new Set(['Currently Using','Open','Unopened / Backup','Nearly Empty','Travel Size','Sample']);
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));

  function api(){return window.IchigoSkincareSort||null;}
  function ensureStyles(){
    if(document.getElementById('ichigoSkincareViewStyles'))return;const style=document.createElement('style');style.id='ichigoSkincareViewStyles';style.textContent=`.topbar{grid-template-columns:44px 1fr 42px 42px!important}#skincareQuickButton{font-size:19px;position:relative}#skincareQuickButton .skincare-count{position:absolute;right:-2px;top:-4px;min-width:17px;height:17px;border-radius:999px;background:var(--rose);color:#fff;display:grid;place-items:center;font-size:8px;font-weight:900;border:2px solid var(--cream-2)}.skincare-hero-card{background:linear-gradient(145deg,#fff,#fff4f7);border:1px solid var(--line);border-radius:24px;padding:16px;display:flex;justify-content:space-between;gap:14px;align-items:center}.skincare-hero-card h2{margin:4px 0 5px;font-size:21px}.skincare-hero-card p{margin:0;color:var(--muted);font-size:12px;line-height:1.45}.skincare-hero-icon{font-size:42px}.skincare-filter-row{display:flex;gap:7px;overflow:auto;padding:3px 0 10px}.skincare-filter-row button{white-space:nowrap;border:1px solid var(--line);background:white;border-radius:999px;padding:9px 12px;color:var(--muted);font-size:10px;font-weight:800}.skincare-filter-row button.active{background:var(--rose);color:#fff;border-color:var(--rose)}@media(max-width:390px){.topbar{grid-template-columns:40px 1fr 40px 40px!important;gap:6px;padding-left:10px;padding-right:10px}.brand-button small{display:none}}`;document.head.appendChild(style);
  }
  function currentSkincare(){const sort=api();return sort?sort.readData().products.filter(sort.isSkincareProduct):[];}
  function updateCount(){const button=document.getElementById('skincareQuickButton'),sort=api();if(!button||!sort)return;const count=currentSkincare().filter(product=>ACTIVE_STATUSES.has(product.status)).length;let badge=button.querySelector('.skincare-count');if(!badge){badge=document.createElement('small');badge.className='skincare-count';button.appendChild(badge);}badge.textContent=count>99?'99+':String(count);badge.classList.toggle('hidden',count===0);button.title=count?`Open my skincare · ${count} active product${count===1?'':'s'}`:'Open my skincare';}
  function productCard(product){const sort=api(),image=product.onlineImage||product.image||'',inferred=!sort.CATEGORY_SET.has(product.category)?sort.smartCategory(product.name):'',category=sort.CATEGORY_SET.has(product.category)?product.category:(inferred||product.category||'Other');return `<article class="product-card" data-skincare-open-product="${esc(product.id)}"><div class="product-thumb">${image?`<img src="${esc(image)}" alt="${esc(product.name||'Product')}" referrerpolicy="no-referrer" loading="lazy">`:'🧴'}</div><div class="product-info"><h3>${esc(product.name||'Untitled product')}</h3><p>${esc(product.onlineBrand||product.brand||'Brand not set')} · ${esc(category)}</p><div class="badges"><span class="badge">${esc(product.status||'Currently Using')}</span>${inferred?'<span class="badge lav">Smart category</span>':''}${product.sourceUrl?'<span class="badge lav">Online info</span>':''}</div></div><button class="card-menu" type="button" aria-label="Open product">›</button></article>`;}
  function openCoreProduct(id){document.querySelector('.nav-item[data-nav="stash"]')?.click();setTimeout(()=>{const target=document.querySelector(`[data-product="${CSS.escape(String(id))}"]`);target?.click();},80);}
  function render(filter='All'){
    const sort=api(),main=document.getElementById('main');if(!sort||!main)return;ensureStyles();const all=currentSkincare(),active=all.filter(product=>ACTIVE_STATUSES.has(product.status)),using=all.filter(product=>product.status==='Currently Using').length,backups=all.filter(product=>product.status==='Unopened / Backup').reduce((sum,product)=>sum+Math.max(1,Number(product.quantity)||1),0),categories=sort.CATEGORIES.filter(category=>all.some(product=>(sort.CATEGORY_SET.has(product.category)?product.category:sort.smartCategory(product.name))===category));const visible=all.filter(product=>filter==='All'||(sort.CATEGORY_SET.has(product.category)?product.category:sort.smartCategory(product.name))===filter).sort((a,b)=>{const ac=sort.CATEGORY_SET.has(a.category)?a.category:sort.smartCategory(a.name),bc=sort.CATEGORY_SET.has(b.category)?b.category:sort.smartCategory(b.name);return sort.CATEGORIES.indexOf(ac)-sort.CATEGORIES.indexOf(bc)||String(a.name).localeCompare(String(b.name));});
    document.querySelectorAll('.nav-item[data-nav]').forEach(button=>button.classList.remove('active'));
    main.innerHTML=`<section class="skincare-hero-card"><div><span class="eyebrow">My skincare</span><h2>Your skincare shelf</h2><p>Skincare only — automatically organized with category rules plus local learning from your corrections.</p></div><div class="skincare-hero-icon">🧴</div></section><div class="card-grid" style="margin-top:12px"><article class="card stat-card"><div class="mini">✦ USING</div><strong>${using}</strong><p>currently using</p></article><article class="card stat-card"><div class="mini">▦ SKINCARE</div><strong>${active.length}</strong><p>active products</p></article><article class="card stat-card"><div class="mini">○ BACKUPS</div><strong>${backups}</strong><p>unopened units</p></article><article class="card stat-card"><div class="mini">☰ TYPES</div><strong>${categories.length}</strong><p>product types</p></article></div><section class="section"><div class="section-head"><h2>Smart organize</h2></div><div class="button-row"><button class="primary" type="button" data-skincare-smart-import>✨ Smart Sort Skincare</button><button class="secondary" type="button" data-skincare-sort-existing>Sort uncategorized</button>${localStorage.getItem(sort.BACKUP_KEY)?'<button class="secondary" type="button" data-skincare-undo>Undo last sort</button>':''}</div></section><section class="section"><div class="section-head"><div><h2>Skincare</h2><p>${all.length} saved skincare product${all.length===1?'':'s'}</p></div></div><div class="skincare-filter-row"><button class="${filter==='All'?'active':''}" data-skincare-filter="All">All</button>${categories.map(category=>`<button class="${filter===category?'active':''}" data-skincare-filter="${esc(category)}">${esc(category)}</button>`).join('')}</div>${visible.length?`<div class="product-list">${visible.map(productCard).join('')}</div>`:'<div class="empty"><div class="empty-icon">🧴</div><h3>No skincare here yet</h3><p>Add or Smart Sort products and they will appear on this shelf automatically.</p></div>'}</section>`;
    main.querySelectorAll('[data-skincare-filter]').forEach(button=>button.addEventListener('click',()=>render(button.dataset.skincareFilter)));main.querySelector('[data-skincare-smart-import]')?.addEventListener('click',sort.openModal);main.querySelector('[data-skincare-sort-existing]')?.addEventListener('click',sort.sortExisting);main.querySelector('[data-skincare-undo]')?.addEventListener('click',sort.undo);main.querySelectorAll('[data-skincare-open-product]').forEach(card=>card.addEventListener('click',()=>openCoreProduct(card.dataset.skincareOpenProduct)));updateCount();
  }
  function bind(){ensureStyles();document.getElementById('skincareQuickButton')?.addEventListener('click',()=>render());document.getElementById('skincareDrawerButton')?.addEventListener('click',()=>{document.getElementById('drawerBackdrop')?.click();setTimeout(()=>render(),20);});document.querySelectorAll('.nav-item[data-nav],.brand-button[data-nav]').forEach(button=>button.addEventListener('click',()=>setTimeout(updateCount,0)));updateCount();window.addEventListener('pageshow',updateCount);window.addEventListener('storage',updateCount);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
